"""TypeScript stub generation for Alpine.js stores and state.

Scans ``.jinja`` templates for ``state`` and ``store`` declarations and
generates ``.d.ts`` stubs so editor tooling can provide autocomplete for
Alpine.js code in ``<script>`` blocks.
"""

from __future__ import annotations

import logging
from pathlib import Path

import json
import re

from pjx.parser import parse_file

logger = logging.getLogger("pjx")

# Mapping from PJX/Python types to TypeScript types
_TYPE_MAP: dict[str, str] = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "list": "any[]",
    "dict": "Record<string, any>",
    "": "any",
}


def _ts_type(py_type: str) -> str:
    """Convert a Python type annotation to a TypeScript type."""
    return _TYPE_MAP.get(py_type, "any")


def _infer_ts_type(value: object) -> str:
    """Infer a TypeScript type from a JSON-parsed value."""
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int | float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "any[]"
    if isinstance(value, dict):
        return "Record<string, any>"
    return "any"


def _infer_fields_from_value(raw_js: str) -> list[tuple[str, str]]:
    """Try to infer field names and types from a raw JS object literal.

    Converts JS-style object to JSON (best effort) and extracts fields.
    Falls back to regex extraction if JSON parsing fails.
    """
    # Try JSON parse (works for simple cases like { "dark": false })
    cleaned = raw_js.strip()
    if cleaned.startswith("{") and cleaned.endswith("}"):
        # Convert JS to JSON: unquoted keys → quoted keys, single → double quotes
        jsonish = re.sub(r"(\w+)\s*:", r'"\1":', cleaned)
        jsonish = jsonish.replace("'", '"')
        # Convert JS booleans/null
        jsonish = (
            jsonish.replace("true", "true")
            .replace("false", "false")
            .replace("null", "null")
        )
        try:
            obj = json.loads(jsonish)
            if isinstance(obj, dict):
                return [(k, _infer_ts_type(v)) for k, v in obj.items()]
        except json.JSONDecodeError:
            pass

    # Fallback: regex to extract key names
    keys = re.findall(r"(\w+)\s*:", cleaned)
    return [(k, "any") for k in keys]


def generate_store_types(templates_dir: Path) -> str:
    """Generate TypeScript declarations for all stores found in templates.

    Args:
        templates_dir: Directory to scan for ``.jinja`` files.

    Returns:
        TypeScript declaration file content.
    """
    stores: dict[str, list[tuple[str, str]]] = {}

    if not templates_dir.exists():
        return ""

    for jinja_file in sorted(templates_dir.rglob("*.jinja")):
        try:
            component = parse_file(jinja_file)
        except Exception:
            continue

        for store in component.stores:
            if store.name:
                fields = _infer_fields_from_value(store.value)
                if fields:
                    stores[store.name] = fields

    if not stores:
        return ""

    lines: list[str] = [
        "// Auto-generated by pjx typegen — do not edit manually",
        "// Provides type definitions for Alpine.js stores",
        "",
        "declare global {",
        "  interface AlpineStores {",
    ]

    for store_name, fields in sorted(stores.items()):
        lines.append(f"    {store_name}: {{")
        for field_name, ts_type in fields:
            lines.append(f"      {field_name}: {ts_type};")
        lines.append("    };")

    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("export {};")
    lines.append("")

    return "\n".join(lines)


def generate_state_types(templates_dir: Path) -> str:
    """Generate TypeScript declarations for component-level state.

    Args:
        templates_dir: Directory to scan for ``.jinja`` files.

    Returns:
        TypeScript declaration file content.
    """
    components: dict[str, list[tuple[str, str]]] = {}

    if not templates_dir.exists():
        return ""

    for jinja_file in sorted(templates_dir.rglob("*.jinja")):
        try:
            component = parse_file(jinja_file)
        except Exception:
            continue

        if component.states:
            name = jinja_file.stem
            fields: list[tuple[str, str]] = []
            for state_decl in component.states:
                fields.append((state_decl.name, "any"))
            if fields:
                components[name] = fields

    if not components:
        return ""

    lines: list[str] = [
        "// Auto-generated by pjx typegen — do not edit manually",
        "// Provides type definitions for component x-data state",
        "",
    ]

    for comp_name, fields in sorted(components.items()):
        lines.append(f"interface {comp_name}State {{")
        for field_name, ts_type in fields:
            lines.append(f"  {field_name}: {ts_type};")
        lines.append("}")
        lines.append("")

    lines.append("export {};")
    lines.append("")

    return "\n".join(lines)


def write_types(
    templates_dir: Path,
    output: Path,
    *,
    filename: str = "pjx-stores.d.ts",
) -> Path | None:
    """Generate and write TypeScript stubs for stores.

    Args:
        templates_dir: Directory to scan for ``.jinja`` files.
        output: Directory to write the ``.d.ts`` file into.
        filename: Output filename.

    Returns:
        Path to the written file, or None if no stores found.
    """
    content = generate_store_types(templates_dir)
    if not content:
        return None

    output.mkdir(parents=True, exist_ok=True)
    out_path = output / filename
    out_path.write_text(content, encoding="utf-8")
    logger.info("typegen → %s", out_path)
    return out_path
